[[plugins]]
  package = "./utils/netlify-plugin-pwa-icon"
  
[build.environment]
  NODE_OPTIONS = "--max_old_space_size=6144"
  
[build]
  base = "./"
  publish = "dist"
  command = "npm run generate"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[build.processing]
  skip_processing = true